//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UkListing
{
    using System;
    using System.Collections.Generic;
    
    public partial class Canada_Prohibited_Keywords
    {
        public int ID { get; set; }
        public string Keywords { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
