//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UkListing
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_WatchesNotPrime
    {
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public string UPC { get; set; }
        public string ASIN { get; set; }
        public string Category { get; set; }
        public string Amount { get; set; }
        public string PackageQty { get; set; }
        public string SalesPrice { get; set; }
        public string Prime { get; set; }
        public Nullable<long> SalesRank { get; set; }
        public string Manufacturer { get; set; }
        public string Features1 { get; set; }
        public string Features2 { get; set; }
        public string Features3 { get; set; }
        public string Features4 { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<int> Status { get; set; }
        public string LargeImageUrl { get; set; }
        public string MediumImageUrl { get; set; }
        public string SmallImageUrl { get; set; }
        public string Brand { get; set; }
        public string Description { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public string FileName { get; set; }
        public Nullable<long> HeightUnits { get; set; }
        public Nullable<long> LengthUnits { get; set; }
        public Nullable<long> WeightUnits { get; set; }
        public Nullable<long> WidthUnits { get; set; }
        public Nullable<int> UK_Prohibited { get; set; }
        public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
        public Nullable<int> Offers_New { get; set; }
        public string UpdatedSalesPrice { get; set; }
        public Nullable<System.DateTime> UpdatedSalesPriceTimeStamp { get; set; }
        public Nullable<int> Instock { get; set; }
        public Nullable<int> ReExportStatus { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> ExportAllStatus { get; set; }
        public Nullable<int> Account1_Status { get; set; }
        public Nullable<System.DateTime> Account1_ExportDate { get; set; }
        public Nullable<int> Account1_ReExport { get; set; }
        public string Account1_FileName { get; set; }
        public Nullable<int> Account2_Status { get; set; }
        public Nullable<System.DateTime> Account2_ExportDate { get; set; }
        public Nullable<int> Account2_ReExport { get; set; }
        public string Account2_FileName { get; set; }
        public Nullable<int> Account3_Status { get; set; }
        public Nullable<System.DateTime> Account3_ExportDate { get; set; }
        public Nullable<int> Account3_ReExport { get; set; }
        public string Account3_FileName { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public short Account4_Status { get; set; }
        public Nullable<System.DateTime> Account4_ExportDate { get; set; }
        public short Account4_ReExport { get; set; }
        public string Account4_FileName { get; set; }
        public short Account1_cmaxExport { get; set; }
        public short Account2_cmaxExport { get; set; }
        public short Account3_cmaxExport { get; set; }
        public short Account4_cmaxExport { get; set; }
        public System.DateTime ReExportTimeStamp { get; set; }
        public string ReExportFileName { get; set; }
        public short CanadaProhibited { get; set; }
        public short ForceExport { get; set; }
    }
}
