//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UkListing
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Account
    {
        public int ID { get; set; }
        public string SellingVenue { get; set; }
        public string MerchantId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Toys { get; set; }
        public Nullable<int> SportingGoods { get; set; }
        public Nullable<int> Beauty { get; set; }
        public Nullable<int> Baby { get; set; }
        public string ShortCode { get; set; }
        public Nullable<int> ReExportAllow { get; set; }
    }
}
