//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UkListing
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Keywords
    {
        public int ID { get; set; }
        public string Keywords { get; set; }
        public Nullable<System.DateTime> BabySearched { get; set; }
        public Nullable<System.DateTime> BeautySearched { get; set; }
        public Nullable<System.DateTime> SportsSearched { get; set; }
        public Nullable<System.DateTime> ToysSearched { get; set; }
        public Nullable<System.DateTime> JewelrySearched { get; set; }
        public Nullable<System.DateTime> WatchesSearched { get; set; }
        public int Priority { get; set; }
    }
}
