//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UkListing
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HomeandKitchen
    {
        public string Title { get; set; }
        public string UPC { get; set; }
        public string ASIN { get; set; }
        public string Category { get; set; }
        public Nullable<float> SalesPrice { get; set; }
        public string Brand { get; set; }
        public string Description { get; set; }
        public Nullable<int> PackageQty { get; set; }
        public Nullable<float> Amount { get; set; }
        public Nullable<short> Prime { get; set; }
        public Nullable<int> SalesRank { get; set; }
        public string LargeImageURL { get; set; }
        public string MediumImageURL { get; set; }
        public string SmallImageURL { get; set; }
        public string Manufacturer { get; set; }
        public string Features1 { get; set; }
        public string Features2 { get; set; }
        public string Features3 { get; set; }
        public string Features4 { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<short> Status { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public string FileName { get; set; }
        public Nullable<int> HeightUnits { get; set; }
        public Nullable<int> LengthUnits { get; set; }
        public Nullable<int> WeightUnits { get; set; }
        public Nullable<int> WidthUnits { get; set; }
        public short UK_Prohibited { get; set; }
        public Nullable<System.DateTime> UpdatedTimeStamp { get; set; }
        public Nullable<short> Offers_New { get; set; }
        public Nullable<float> UpdatedSalesPrice { get; set; }
        public Nullable<System.DateTime> UpdatedSalesPriceTimeStamp { get; set; }
        public Nullable<short> Instock { get; set; }
        public Nullable<short> ReExportStatus { get; set; }
        public Nullable<short> Qty { get; set; }
        public Nullable<short> ImportFromNonPrime { get; set; }
        public Nullable<short> ExportAllStatus { get; set; }
        public Nullable<short> Account1_Status { get; set; }
        public Nullable<System.DateTime> Account1_ExportDate { get; set; }
        public Nullable<short> Account1_ReExport { get; set; }
        public string Account1_FileName { get; set; }
        public Nullable<short> Account2_Status { get; set; }
        public Nullable<System.DateTime> Account2_ExportDate { get; set; }
        public Nullable<short> Account2_ReExport { get; set; }
        public string Account2_FileName { get; set; }
        public Nullable<short> Account3_Status { get; set; }
        public Nullable<System.DateTime> Account3_ExportDate { get; set; }
        public Nullable<short> Account3_ReExport { get; set; }
        public string Account3_FileName { get; set; }
        public Nullable<short> CanadaProhibited { get; set; }
        public Nullable<short> ForceExport { get; set; }
        public Nullable<System.DateTime> ReExportTimeStamp { get; set; }
        public string ReExportFileName { get; set; }
        public Nullable<short> account1_cmaxexport { get; set; }
        public Nullable<short> account2_cmaxexport { get; set; }
        public Nullable<short> account3_cmaxexport { get; set; }
        public Nullable<short> Account4_Status { get; set; }
        public Nullable<System.DateTime> Account4_ExportDate { get; set; }
        public Nullable<int> Account4_ReExport { get; set; }
        public string Account4_FileName { get; set; }
        public Nullable<short> FakeUPC { get; set; }
    }
}
