//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmazonInventory
    {
        public AmazonInventory()
        {
            this.AmazonInventorySKUs = new HashSet<AmazonInventorySKU>();
        }
    
        public System.Guid AmazonAccountID { get; set; }
        public string ASIN { get; set; }
        public Nullable<decimal> AmazonStockQty { get; set; }
        public Nullable<System.DateTime> AmazonStockTimeStamp { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> LastKnownListingOpenDate { get; set; }
        public Nullable<decimal> LastKnownListingPrice { get; set; }
        public Nullable<System.DateTime> UnderPricedIgnoreUntilUpdate { get; set; }
        public Nullable<System.DateTime> UnderPricedIgnoreUntil { get; set; }
        public Nullable<decimal> AmazonInStockQty { get; set; }
    
        public virtual AmazonAccount AmazonAccount { get; set; }
        public virtual ICollection<AmazonInventorySKU> AmazonInventorySKUs { get; set; }
        public virtual KnownASIN KnownASIN { get; set; }
    }
}
