//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmazonOrder
    {
        public AmazonOrder()
        {
            this.AmazonOrderLines = new HashSet<AmazonOrderLine>();
        }
    
        public System.Guid AmazonAccountID { get; set; }
        public string AmazonOrderID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string NameFirst { get; set; }
        public string NameLast { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipAddress3 { get; set; }
        public string ShipCity { get; set; }
        public string ShipStateProvince { get; set; }
        public Nullable<int> ShipStateID { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipCountryCode { get; set; }
        public Nullable<int> ShipCountryID { get; set; }
        public string ShipPhone { get; set; }
        public Nullable<int> FulfillmentChannel { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> LastStatusChangeNoticed { get; set; }
        public Nullable<System.Guid> ProductInventoryAdjustmentBatchID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Email { get; set; }
        public string SOSInventoryChangeReportID { get; set; }
        public string ShipToName { get; set; }
    
        public virtual AmazonAccount AmazonAccount { get; set; }
        public virtual ICollection<AmazonOrderLine> AmazonOrderLines { get; set; }
        public virtual ProductInventoryAdjustmentBatch ProductInventoryAdjustmentBatch { get; set; }
    }
}
