//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmazonOrderLine
    {
        public System.Guid AmazonAccountID { get; set; }
        public string AmazonOrderID { get; set; }
        public int LineNumber { get; set; }
        public string ASIN { get; set; }
        public decimal Price { get; set; }
        public decimal Qty { get; set; }
        public string Name { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<decimal> OrderItemID { get; set; }
        public Nullable<System.Guid> NotShippedFromWarehouseID { get; set; }
    
        public virtual ProductInventoryAdjustment ProductInventoryAdjustment { get; set; }
        public virtual AmazonOrder AmazonOrder { get; set; }
    }
}
