//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmazonAccount
    {
        public AmazonAccount()
        {
            this.AmazonInventories = new HashSet<AmazonInventory>();
            this.AmazonInventorySKUs = new HashSet<AmazonInventorySKU>();
            this.FeedSubmissionSchedules = new HashSet<FeedSubmissionScheduleRec>();
            this.FeedSubmissionQueues = new HashSet<FeedSubmissionQueueRec>();
            this.InboundFBAShipments = new HashSet<InboundFBAShipment>();
            this.AmazonOrders = new HashSet<AmazonOrder>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string SecretAccessKey { get; set; }
        public string MerchantID { get; set; }
        public string AccessKeyID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int ShortID { get; set; }
        public Nullable<System.DateTime> LastInventoryUpdate { get; set; }
        public Nullable<System.DateTime> LastInventoryUpdateStart { get; set; }
        public string CharID { get; set; }
        public int CountryID { get; set; }
        public string DateTimeFormat { get; set; }
        public Nullable<System.DateTime> LastSyncSKU { get; set; }
        public Nullable<System.DateTime> LastOrderHistoryReportStartDate { get; set; }
        public Nullable<int> DisplaySeq { get; set; }
        public bool DoTrafficImport { get; set; }
        public Nullable<System.DateTime> LastFBAInboundShipmentSync { get; set; }
        public System.DateTime LastGetSettlementData { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<AmazonInventory> AmazonInventories { get; set; }
        public virtual ICollection<AmazonInventorySKU> AmazonInventorySKUs { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<FeedSubmissionScheduleRec> FeedSubmissionSchedules { get; set; }
        public virtual ICollection<FeedSubmissionQueueRec> FeedSubmissionQueues { get; set; }
        public virtual ICollection<InboundFBAShipment> InboundFBAShipments { get; set; }
        public virtual ICollection<AmazonOrder> AmazonOrders { get; set; }
    }
}
