//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmazonInventorySKU
    {
        public System.Guid AmazonAccountID { get; set; }
        public string ASIN { get; set; }
        public string SKU { get; set; }
        public Nullable<decimal> InStockQty { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public string ListingID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<int> ItemCondition { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> UpdateTimeStamp { get; set; }
        public bool Disabled { get; set; }
        public bool IgnoreForFBAInventoryDeduction { get; set; }
    
        public virtual AmazonAccount AmazonAccount { get; set; }
        public virtual KnownASIN KnownASIN { get; set; }
        public virtual AmazonInventory AmazonInventory { get; set; }
    }
}
