//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmazonInventoryView
    {
        public string ASIN { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> AmazonStockQty { get; set; }
        public Nullable<System.DateTime> AmazonStockTimeStamp { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
