//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmazonInventoryProduct
    {
        public string ASIN { get; set; }
        public System.Guid ProductID { get; set; }
        public decimal Qty { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual KnownASIN KnownASIN { get; set; }
        public virtual Product Product { get; set; }
    }
}
