//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASINOfferListing
    {
        public System.Guid ID { get; set; }
        public string ASIN { get; set; }
        public string MerchantID { get; set; }
        public bool AmazonFulfilled { get; set; }
        public decimal Price { get; set; }
        public string PricePerUnit { get; set; }
        public Nullable<decimal> ShippingPrice { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> UpdateTimeStamp { get; set; }
        public int CountryID { get; set; }
        public byte[] OfferingIDDecoded { get; set; }
    
        public virtual KnownASIN KnownASIN { get; set; }
    }
}
