//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomaticPriceChange
    {
        public System.Guid ID { get; set; }
        public string SKU { get; set; }
        public decimal TempPrice { get; set; }
        public decimal RegularPrice { get; set; }
        public System.Guid StartFeedSubmissionScheduleID { get; set; }
        public System.Guid EndFeedSubmissionScheduleID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string TimeSpan { get; set; }
        public System.DateTime TempPriceStartDateTime { get; set; }
        public System.DateTime TempPriceEndDateTime { get; set; }
        public System.Guid AmazonAccountID { get; set; }
        public string ASIN { get; set; }
    
        public virtual FeedSubmissionQueueRec StartFeedSubmissionSchedule { get; set; }
        public virtual FeedSubmissionQueueRec EndFeedSubmissionSchedule { get; set; }
        public virtual FeedSubmissionScheduleRec FeedSubmissionSchedule { get; set; }
        public virtual FeedSubmissionScheduleRec FeedSubmissionSchedule1 { get; set; }
    }
}
