//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyTraffic
    {
        public System.DateTime Date { get; set; }
        public System.Guid AmazonAccountID { get; set; }
        public string ASIN { get; set; }
        public string SKU { get; set; }
        public int Sessions { get; set; }
        public decimal SessionPercentage { get; set; }
        public int PageViews { get; set; }
        public decimal PageViewPercentage { get; set; }
        public decimal BuyBoxPercentage { get; set; }
        public int UnitsOrdered { get; set; }
        public decimal UnitSessionPercentage { get; set; }
        public decimal OrderedProductSales { get; set; }
        public int TotalOrderItems { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
