//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eBayItem
    {
        public string ItemID { get; set; }
        public Nullable<decimal> CurrentPrice { get; set; }
        public string Title { get; set; }
        public string ListingStatusText { get; set; }
        public Nullable<int> ListingStatus { get; set; }
        public Nullable<int> ProductAssociationCount { get; set; }
    }
}
