//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eBayRawItemData
    {
        public eBayRawItemData()
        {
            this.eBayItemsProducts = new HashSet<eBayItemsProduct>();
            this.eBayOrderLines = new HashSet<eBayOrderLine>();
        }
    
        public string ItemID { get; set; }
        public string RawData { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> UpdateTimeStamp { get; set; }
    
        public virtual ICollection<eBayItemsProduct> eBayItemsProducts { get; set; }
        public virtual ICollection<eBayOrderLine> eBayOrderLines { get; set; }
    }
}
