//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eBayOrderLine
    {
        public string ID { get; set; }
        public string OrderID { get; set; }
        public string ItemID { get; set; }
        public decimal Qty { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> UpdateTimeStamp { get; set; }
        public int SellingManagerSalesRecordNumber { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual eBayOrder eBayOrder { get; set; }
        public virtual eBayRawItemData eBayRawItemData { get; set; }
    }
}
