//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eBayOrder
    {
        public eBayOrder()
        {
            this.eBayOrderLines = new HashSet<eBayOrderLine>();
        }
    
        public string ID { get; set; }
        public string RawData { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.Guid> ProductInventoryMoveID { get; set; }
        public Nullable<System.DateTime> UpdateTimeStamp { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ShippedNoticedTimeStamp { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> ShippedTime { get; set; }
        public string Site { get; set; }
    
        public virtual ProductInventoryAdjustmentBatch ProductInventoryAdjustmentBatch { get; set; }
        public virtual ICollection<eBayOrderLine> eBayOrderLines { get; set; }
    }
}
