//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportSpec
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string FieldList { get; set; }
        public string WhereClause { get; set; }
        public string OrderByClause { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> UpdateTimeStamp { get; set; }
        public string FieldNameTranslations { get; set; }
        public string SelectClauseExtension { get; set; }
        public Nullable<int> RecordCount { get; set; }
        public string FromClauseExtension { get; set; }
        public string FileHeaderText { get; set; }
        public string FieldDelimiter { get; set; }
        public string FileExtension { get; set; }
        public bool EncloseInQuotes { get; set; }
        public Nullable<System.Guid> ExcludeExportsToSalesVenueID { get; set; }
    
        public virtual SalesVenue SalesVenue { get; set; }
    }
}
