//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FakeUPC
    {
        public string UPC { get; set; }
        public string ProductComboCode { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.Guid> BatchID { get; set; }
        public string SKU { get; set; }
    }
}
