//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedSubmissionScheduleRec
    {
        public FeedSubmissionScheduleRec()
        {
            this.FeedSubmissionQueueRecs = new HashSet<FeedSubmissionQueueRec>();
            this.AutomaticPriceChanges = new HashSet<AutomaticPriceChange>();
            this.AutomaticPriceChanges1 = new HashSet<AutomaticPriceChange>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid AmazonAccountID { get; set; }
        public string FeedType { get; set; }
        public string MessageType { get; set; }
        public string MessageXML { get; set; }
        public System.DateTime NextRun { get; set; }
        public string TimeSpan { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public bool MustRunAll { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> Deleted { get; set; }
    
        public virtual AmazonAccount AmazonAccount { get; set; }
        public virtual ICollection<FeedSubmissionQueueRec> FeedSubmissionQueueRecs { get; set; }
        public virtual ICollection<AutomaticPriceChange> AutomaticPriceChanges { get; set; }
        public virtual ICollection<AutomaticPriceChange> AutomaticPriceChanges1 { get; set; }
    }
}
