//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboundFBAShipmentItem
    {
        public string ShipmentID { get; set; }
        public string SKU { get; set; }
        public Nullable<decimal> QuantityShipped { get; set; }
        public Nullable<decimal> QuantityReceived { get; set; }
        public Nullable<decimal> QuantityInCase { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> UpdateTimeStamp { get; set; }
    
        public virtual InboundFBAShipment InboundFBAShipment { get; set; }
    }
}
