//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboundFBAShipmentManagementView
    {
        public System.DateTime OrderBy { get; set; }
        public string ID { get; set; }
        public System.Guid AmazonAccountID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ItemCount { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> UpdateTimeStamp { get; set; }
        public Nullable<System.DateTime> RemovedFromInventoryAdjustmentProcessing { get; set; }
        public Nullable<System.DateTime> ScheduledForInventoryAdjustmentProcessing { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string InboundFBAShipmentID { get; set; }
        public Nullable<System.DateTime> FirstInventoryAdjustment { get; set; }
        public Nullable<System.DateTime> LastInventoryAdjustment { get; set; }
        public Nullable<int> InventoryAdjustmentCount { get; set; }
        public string AmazonAccountName { get; set; }
    }
}
