//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboundFBAShipment
    {
        public InboundFBAShipment()
        {
            this.InboundFBAShipmentStatusChanges = new HashSet<InboundFBAShipmentStatusChange>();
            this.InboundFBAShipmentItems = new HashSet<InboundFBAShipmentItem>();
            this.InboundFBAShipmentProductInventoryAdjustments = new HashSet<InboundFBAShipmentProductInventoryAdjustment>();
        }
    
        public string ID { get; set; }
        public System.Guid AmazonAccountID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ItemCount { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> UpdateTimeStamp { get; set; }
        public Nullable<System.DateTime> RemovedFromInventoryAdjustmentProcessing { get; set; }
        public Nullable<System.DateTime> ScheduledForInventoryAdjustmentProcessing { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual AmazonAccount AmazonAccount { get; set; }
        public virtual ICollection<InboundFBAShipmentStatusChange> InboundFBAShipmentStatusChanges { get; set; }
        public virtual ICollection<InboundFBAShipmentItem> InboundFBAShipmentItems { get; set; }
        public virtual ICollection<InboundFBAShipmentProductInventoryAdjustment> InboundFBAShipmentProductInventoryAdjustments { get; set; }
    }
}
