//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnownASIN
    {
        public KnownASIN()
        {
            this.AmazonInventoryProducts = new HashSet<AmazonInventoryProduct>();
            this.AmazonInventorySKUs = new HashSet<AmazonInventorySKU>();
            this.KnownASINAttributes = new HashSet<KnownASINAttribute>();
            this.ASINsSuccessfullyExporteds = new HashSet<ASINsSuccessfullyExported>();
            this.ASINOfferListings = new HashSet<ASINOfferListing>();
            this.ASINOfferScrapes = new HashSet<ASINOfferScrape>();
            this.AmazonInventories = new HashSet<AmazonInventory>();
        }
    
        public string ASIN { get; set; }
        public string SearchTerm { get; set; }
        public string Title { get; set; }
        public bool Filtered { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> LastSeen { get; set; }
        public Nullable<System.DateTime> Reviewed { get; set; }
        public bool OurProduct { get; set; }
        public string MarketPlaceID { get; set; }
        public Nullable<System.DateTime> LastScrape { get; set; }
        public Nullable<decimal> OurLowestPrice { get; set; }
        public Nullable<System.DateTime> LastScrapeTry { get; set; }
        public Nullable<System.DateTime> FirstScrapeFail { get; set; }
        public Nullable<System.DateTime> LastScrapeFail { get; set; }
        public Nullable<int> ScrapeFailCount { get; set; }
        public bool GoneFromAmazon { get; set; }
        public Nullable<decimal> OurMostRecentUSListingPrice { get; set; }
        public Nullable<System.DateTime> OurMostRecentUSListingOpenDate { get; set; }
        public Nullable<System.Guid> OurMostRecentUSListingAccountID { get; set; }
        public string ImageName { get; set; }
        public string MergedIntoASIN { get; set; }
    
        public virtual ICollection<AmazonInventoryProduct> AmazonInventoryProducts { get; set; }
        public virtual ICollection<AmazonInventorySKU> AmazonInventorySKUs { get; set; }
        public virtual ICollection<KnownASINAttribute> KnownASINAttributes { get; set; }
        public virtual ICollection<ASINsSuccessfullyExported> ASINsSuccessfullyExporteds { get; set; }
        public virtual ICollection<ASINOfferListing> ASINOfferListings { get; set; }
        public virtual ICollection<ASINOfferScrape> ASINOfferScrapes { get; set; }
        public virtual ICollection<AmazonInventory> AmazonInventories { get; set; }
    }
}
