//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AmazonAccount> AmazonAccounts { get; set; }
        public DbSet<SearchTerm> SearchTerms { get; set; }
        public DbSet<KnownASIN> KnownASINs { get; set; }
        public DbSet<SearchTermsWithLastSearchTimeStamp> SearchTermsWithLastSearchTimeStamps { get; set; }
        public DbSet<AmazonInventoryProduct> AmazonInventoryProducts { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<AmazonInventoryView> AmazonInventoryViews { get; set; }
        public DbSet<AmazonInventory> AmazonInventories { get; set; }
        public DbSet<KnownASINsInventoryMaintenanceView> KnownASINsInventoryMaintenanceViews { get; set; }
        public DbSet<RelatedProduct> RelatedProducts { get; set; }
        public DbSet<AmazonInventorySKU> AmazonInventorySKUs { get; set; }
        public DbSet<ReceivedShipment> ReceivedShipments { get; set; }
        public DbSet<Vendor> Vendors { get; set; }
        public DbSet<PurchaseOrderLine> PurchaseOrderLines { get; set; }
        public DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public DbSet<PurchaseOrderStatus> PurchaseOrderStatuses { get; set; }
        public DbSet<ReceivedProduct> ReceivedProducts { get; set; }
        public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<PurchaseOrderPaymentType> PurchaseOrderPaymentTypes { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<supplier> suppliers { get; set; }
        public DbSet<ReportActionParameter> ReportActionParameters { get; set; }
        public DbSet<ReportAction> ReportActions { get; set; }
        public DbSet<KnownASINAttribute> KnownASINAttributes { get; set; }
        public DbSet<TimeZone> TimeZones { get; set; }
        public DbSet<ExportSpec> ExportSpecs { get; set; }
        public DbSet<ASINsSuccessfullyExported> ASINsSuccessfullyExporteds { get; set; }
        public DbSet<SalesVenue> SalesVenues { get; set; }
        public DbSet<OrdersView> OrdersViews { get; set; }
        public DbSet<ProductsView> ProductsView { get; set; }
        public DbSet<ProductCategory> ProductCategories { get; set; }
        public DbSet<ProductTag> ProductTags { get; set; }
        public DbSet<ProductView> ProductView { get; set; }
        public DbSet<FeedSubmissionQueueRec> FeedSubmissionQueue { get; set; }
        public DbSet<FeedSubmissionScheduleRec> FeedSubmissionSchedule { get; set; }
        public DbSet<FeedSubmissionScheduleStatusRec> FeedSubmissionScheduleStatuses { get; set; }
        public DbSet<AutomaticPriceChange> AutomaticPriceChanges { get; set; }
        public DbSet<AutomaticPriceChangesView> AutomaticPriceChangesView { get; set; }
        public DbSet<ASINOfferListing> ASINOfferListings { get; set; }
        public DbSet<ASINOfferScrape> ASINOfferScrapes { get; set; }
        public DbSet<OurListing> OurListings { get; set; }
        public DbSet<OfferScrapeStatus> OfferScrapeStatuses { get; set; }
        public DbSet<UnderPricedViewRec> UnderPricedView { get; set; }
        public DbSet<OnOrder> OnOrders { get; set; }
        public DbSet<DailyTraffic> DailyTraffics { get; set; }
        public DbSet<NeedInInventoryWithTotal> NeedInInventoryWithTotals { get; set; }
        public DbSet<OutPriced> OutPriceds { get; set; }
        public DbSet<SpecialPriceSalesByDay> SpecialPriceSalesByDays { get; set; }
        public DbSet<PurchaseOrderProductsVendor> PurchaseOrderProductsVendors { get; set; }
        public DbSet<SOSInventoryChangeReport> SOSInventoryChangeReports { get; set; }
        public DbSet<eBayRawItemData> eBayRawItemDatas { get; set; }
        public DbSet<SystemStatu> SystemStatus { get; set; }
        public DbSet<eBayItemsProduct> eBayItemsProducts { get; set; }
        public DbSet<ProductInventory> ProductInventories { get; set; }
        public DbSet<InboundFBAShipmentStatusChange> InboundFBAShipmentStatusChanges { get; set; }
        public DbSet<InboundFBAShipment> InboundFBAShipments { get; set; }
        public DbSet<AmazonOrderLine> AmazonOrderLines { get; set; }
        public DbSet<eBayOrder> eBayOrders { get; set; }
        public DbSet<ProductInventoryAdjustmentBatch> ProductInventoryAdjustmentBatches { get; set; }
        public DbSet<ProductInventoryAdjustmentReason> ProductInventoryAdjustmentReasons { get; set; }
        public DbSet<ProductInventoryAdjustmentReasonType> ProductInventoryAdjustmentReasonTypes { get; set; }
        public DbSet<ProductInventoryAdjustment> ProductInventoryAdjustments { get; set; }
        public DbSet<ProductInventoryLocation> ProductInventoryLocations { get; set; }
        public DbSet<InboundFBAShipmentItem> InboundFBAShipmentItems { get; set; }
        public DbSet<AmazonOrder> AmazonOrders { get; set; }
        public DbSet<eBayOrderLine> eBayOrderLines { get; set; }
        public DbSet<FakeUPC> FakeUPCs { get; set; }
        public DbSet<eBayItem> eBayItems { get; set; }
        public DbSet<InboundFBAShipmentProductInventoryAdjustment> InboundFBAShipmentProductInventoryAdjustments { get; set; }
        public DbSet<InboundFBAShipmentManagementView> InboundFBAShipmentManagementViews { get; set; }
        public DbSet<PurchaseOrderConfirm_Status> PurchaseOrderConfirm_Status { get; set; }
        public DbSet<RecievedShipmentStatus> RecievedShipmentStatuses { get; set; }
        public DbSet<ShippedtoAmazon> ShippedtoAmazons { get; set; }
    }
}
