//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersView
    {
        public string AccountName { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string NameFirst { get; set; }
        public string NameLast { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipAddress3 { get; set; }
        public string Shipcity { get; set; }
        public string ShipStateProvince { get; set; }
        public string ShipPostalCode { get; set; }
        public string ShipCountryCode { get; set; }
        public string ShipPhone { get; set; }
        public string ASIN { get; set; }
        public string ProductName { get; set; }
    }
}
