//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutPriced
    {
        public string ASIN { get; set; }
        public Nullable<decimal> CompetitorMinPrice { get; set; }
        public Nullable<int> AmazonFulfilled { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public Nullable<decimal> OurMinPrice { get; set; }
        public string Title { get; set; }
    }
}
