//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.AmazonInventoryProducts = new HashSet<AmazonInventoryProduct>();
            this.PurchaseOrderLines = new HashSet<PurchaseOrderLine>();
            this.ReceivedProducts = new HashSet<ReceivedProduct>();
            this.Vendors = new HashSet<Vendor>();
            this.Categories = new HashSet<ProductCategory>();
            this.Tags = new HashSet<ProductTag>();
            this.eBayItemsProducts = new HashSet<eBayItemsProduct>();
            this.ProductInventories = new HashSet<ProductInventory>();
            this.ProductInventoryAdjustments = new HashSet<ProductInventoryAdjustment>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
        public Nullable<decimal> Weight { get; set; }
    
        public virtual ICollection<AmazonInventoryProduct> AmazonInventoryProducts { get; set; }
        public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; }
        public virtual ICollection<ReceivedProduct> ReceivedProducts { get; set; }
        public virtual ICollection<Vendor> Vendors { get; set; }
        public virtual ICollection<ProductCategory> Categories { get; set; }
        public virtual ICollection<ProductTag> Tags { get; set; }
        public virtual ICollection<eBayItemsProduct> eBayItemsProducts { get; set; }
        public virtual ICollection<ProductInventory> ProductInventories { get; set; }
        public virtual ICollection<ProductInventoryAdjustment> ProductInventoryAdjustments { get; set; }
    }
}
