//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInventoryAdjustmentBatch
    {
        public ProductInventoryAdjustmentBatch()
        {
            this.eBayOrders = new HashSet<eBayOrder>();
            this.ProductInventoryAdjustments = new HashSet<ProductInventoryAdjustment>();
            this.AmazonOrders = new HashSet<AmazonOrder>();
            this.InboundFBAShipmentProductInventoryAdjustments = new HashSet<InboundFBAShipmentProductInventoryAdjustment>();
        }
    
        public System.Guid ID { get; set; }
        public string Type { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual ICollection<eBayOrder> eBayOrders { get; set; }
        public virtual ICollection<ProductInventoryAdjustment> ProductInventoryAdjustments { get; set; }
        public virtual ICollection<AmazonOrder> AmazonOrders { get; set; }
        public virtual ICollection<InboundFBAShipmentProductInventoryAdjustment> InboundFBAShipmentProductInventoryAdjustments { get; set; }
    }
}
