//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInventoryLocation
    {
        public ProductInventoryLocation()
        {
            this.ProductInventories = new HashSet<ProductInventory>();
            this.ProductInventoryAdjustments = new HashSet<ProductInventoryAdjustment>();
        }
    
        public System.Guid ID { get; set; }
        public string ShortCode { get; set; }
        public Nullable<int> Seq { get; set; }
        public string Name { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual ICollection<ProductInventory> ProductInventories { get; set; }
        public virtual ICollection<ProductInventoryAdjustment> ProductInventoryAdjustments { get; set; }
    }
}
