//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInventory
    {
        public System.Guid ProductID { get; set; }
        public System.Guid LocationID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> UpdateTimeStamp { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductInventoryLocation ProductInventoryLocation { get; set; }
    }
}
