//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInventoryAdjustmentReason
    {
        public ProductInventoryAdjustmentReason()
        {
            this.ProductInventoryAdjustments = new HashSet<ProductInventoryAdjustment>();
        }
    
        public System.Guid ID { get; set; }
        public string ShortCode { get; set; }
        public Nullable<int> Seq { get; set; }
        public string Types { get; set; }
        public string Text { get; set; }
        public string ReasonRef1Text { get; set; }
        public Nullable<bool> ReasonRef1Required { get; set; }
        public string ReasonRef2Text { get; set; }
        public Nullable<bool> ReasonRef2Required { get; set; }
        public string ReasonRef3Text { get; set; }
        public Nullable<bool> ReasonRef3Required { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual ICollection<ProductInventoryAdjustment> ProductInventoryAdjustments { get; set; }
    }
}
