//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInventoryAdjustment
    {
        public ProductInventoryAdjustment()
        {
            this.AmazonOrderLines = new HashSet<AmazonOrderLine>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid ProductID { get; set; }
        public System.Guid LocationID { get; set; }
        public System.Guid ReasonID { get; set; }
        public string ReasonRef1 { get; set; }
        public string ReasonRef2 { get; set; }
        public string ReasonRef3 { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public decimal AdjustmentAmount { get; set; }
        public Nullable<decimal> OldQty { get; set; }
        public Nullable<decimal> NewQty { get; set; }
        public Nullable<System.Guid> ProductInventoryAdjustmentBatchID { get; set; }
    
        public virtual ICollection<AmazonOrderLine> AmazonOrderLines { get; set; }
        public virtual ProductInventoryAdjustmentBatch ProductInventoryAdjustmentBatch { get; set; }
        public virtual ProductInventoryAdjustmentReason ProductInventoryAdjustmentReason { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductInventoryLocation ProductInventoryLocation { get; set; }
    }
}
