//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductView
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> ActualCost { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Categories { get; set; }
        public string Tags { get; set; }
        public Nullable<decimal> Weight { get; set; }
    }
}
