//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderProductsVendor
    {
        public System.Guid POID { get; set; }
        public int PONumber { get; set; }
        public System.Guid ProductID { get; set; }
        public System.Guid VendorID { get; set; }
    }
}
