//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public PurchaseOrder()
        {
            this.Lines = new HashSet<PurchaseOrderLine>();
        }
    
        public System.Guid ID { get; set; }
        public System.DateTime Date { get; set; }
        public int Number { get; set; }
        public System.Guid VendorID { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public bool MissingCosts { get; set; }
        public Nullable<System.Guid> PaymentTypeID { get; set; }
        public Nullable<decimal> TotalActualCost { get; set; }
        public string CStatus { get; set; }
    
        public virtual ICollection<PurchaseOrderLine> Lines { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual PurchaseOrderStatus PurchaseOrderStatus { get; set; }
        public virtual PurchaseOrderPaymentType PaymentType { get; set; }
        public virtual PurchaseOrderConfirm_Status PurchaseOrderConfirm_Status { get; set; }
    }
}
