//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivedShipment
    {
        public ReceivedShipment()
        {
            this.ReceivedProducts = new HashSet<ReceivedProduct>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> VendorID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<ReceivedProduct> ReceivedProducts { get; set; }
    }
}
