//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivedProduct
    {
        public ReceivedProduct()
        {
            this.PurchaseOrderLines = new HashSet<PurchaseOrderLine>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ReceivedShipmentID { get; set; }
        public int Number { get; set; }
        public System.Guid ProductID { get; set; }
        public decimal Qty { get; set; }
        public string TrackingNumber { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Status { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<PurchaseOrderLine> PurchaseOrderLines { get; set; }
        public virtual ReceivedShipment ReceivedShipment { get; set; }
        public virtual RecievedShipmentStatus RecievedShipmentStatus { get; set; }
    }
}
