//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportActionParameter
    {
        public System.Guid ReportActionID { get; set; }
        public string ParameterName { get; set; }
        public string ParameterValue { get; set; }
    
        public virtual ReportAction ReportAction { get; set; }
    }
}
