//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportAction
    {
        public ReportAction()
        {
            this.ReportActionParameters = new HashSet<ReportActionParameter>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid AmazonAccountID { get; set; }
        public string ReportType { get; set; }
        public string ReportRequestID { get; set; }
        public string ProcessingMethod { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> ReportCompleted { get; set; }
        public string ReportID { get; set; }
        public Nullable<System.DateTime> ProcessingStarted { get; set; }
        public Nullable<System.DateTime> ProcessingComplete { get; set; }
        public string ProcessingResult { get; set; }
        public Nullable<System.DateTime> ReportDataSaved { get; set; }
        public string ReportDataDownloadLog { get; set; }
    
        public virtual ICollection<ReportActionParameter> ReportActionParameters { get; set; }
    }
}
