//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippedtoAmazon
    {
        public System.Guid ID { get; set; }
        public string ShipmentID { get; set; }
        public string AccountID { get; set; }
        public string AccountName { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Status { get; set; }
    }
}
