//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialPriceSalesByDay
    {
        public string ASIN { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public decimal Qty { get; set; }
        public string Title { get; set; }
        public decimal SpecialPrice { get; set; }
    }
}
