//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Vendors = new HashSet<Vendor>();
        }
    
        public int FIPS { get; set; }
        public string StateName { get; set; }
        public string Code { get; set; }
        public string Abbrev { get; set; }
        public string DrawCoordinates { get; set; }
        public Nullable<int> MapNumber { get; set; }
        public string MapSize { get; set; }
    
        public virtual ICollection<Vendor> Vendors { get; set; }
    }
}
