//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public System.Guid ID { get; set; }
        public string Company { get; set; }
        public string PhoneNumber { get; set; }
        public string Firstname { get; set; }
        public string MidInitial { get; set; }
        public string Lastname { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string ZIP { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string TLD { get; set; }
        public string Email { get; set; }
        public string FaxNumber { get; set; }
    }
}
