//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemStatu
    {
        public System.Guid Key { get; set; }
        public System.DateTime LastSearch { get; set; }
        public Nullable<System.DateTime> LastUpdateSalesPerDayByASINTable { get; set; }
        public Nullable<System.DateTime> OldesteBayRawItemQueryDate { get; set; }
        public Nullable<System.DateTime> LatesteBayRawItemQueryDate { get; set; }
        public Nullable<System.DateTime> LasteBayOrderDownloadQueryDate { get; set; }
    }
}
