//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmnimarkAmazon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnderPricedViewRec
    {
        public string ASIN { get; set; }
        public System.Guid AmazonAccountID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string SKU { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public string Source { get; set; }
        public Nullable<decimal> SystemActualCost { get; set; }
        public string StoreName { get; set; }
        public Nullable<decimal> CalculatedMinimumPrice { get; set; }
        public Nullable<System.DateTime> UnderPricedIgnoreUntilUpdate { get; set; }
        public Nullable<System.DateTime> UnderPricedIgnoreUntil { get; set; }
    }
}
